# =============================================================================
#  biotechnology.branches.red.molecular_diagnostics.governance
# -----------------------------------------------------------------------------
#  FACET 5 OF 6:  GOVERNANCE
#
#  Contract, and the regulations-versus-standards distinction:
#  `red/gene_therapy/governance.py`.
#
#  SUBTYPE-SPECIFIC NOTE
#  The governance of diagnostics turns on a distinction that has no equivalent
#  elsewhere in the red branch: the difference between a DEVICE placed on the
#  market and a TEST performed as a service.
#
#  A manufacturer selling a kit is regulated as a device maker. A hospital
#  laboratory that designs its own assay and runs it on its own patients has,
#  historically, not been. That gap is where most rare-disease and most
#  outbreak-response testing has always lived, because no manufacturer will
#  certify an assay for two hundred patients a year worldwide.
#
#  Both the European Union, through Regulation (EU) 2017/746, and the United
#  States have been closing that gap. The closure improves oversight and
#  simultaneously removes assays that will never be commercially viable. Both
#  halves of that sentence are true, and `practice.CHALLENGES` says so.
#
#  SPDX-License-Identifier: EUPL-1.2
# =============================================================================

from __future__ import annotations

from typing import Tuple

from ....core.enums import Domain, Maturity, RegulatoryStatus, RiskTier, Scale

__all__ = [
    "MATURITY",
    "RISK_TIER",
    "SCALE",
    "DOMAINS",
    "REGULATORY_STATUS",
    "REGULATIONS",
    "STANDARDS",
]


# =============================================================================
#  POSITION IN THE CONTROLLED VOCABULARIES
# =============================================================================

# -----------------------------------------------------------------------------
#  MATURITY = ESTABLISHED.
#  PCR has been routine clinical practice for three decades and is performed
#  billions of times a year. Individual modalities inside the record are newer,
#  and metagenomic diagnosis would be EMERGING on its own, but the practice as
#  a whole is not.
# -----------------------------------------------------------------------------
MATURITY = Maturity.ESTABLISHED

# -----------------------------------------------------------------------------
#  RISK_TIER = REGULATED.
#  A commercial assay needs conformity assessment before it may be sold, and
#  the laboratory performing it needs accreditation. Two separate gates, held
#  by two separate bodies.
# -----------------------------------------------------------------------------
RISK_TIER = RiskTier.REGULATED

# -----------------------------------------------------------------------------
#  SCALE = BENCH.
#  The unit of work is one specimen. Population screening programmes are
#  population-scale activities built out of bench-scale tests, and the
#  distinction matters: the arithmetic in metrics.py is exactly what happens
#  when a bench-scale test is applied at population scale.
# -----------------------------------------------------------------------------
SCALE = Scale.BENCH

# -----------------------------------------------------------------------------
#  DOMAINS
#  HEALTH is the purpose. INFORMATION is included because a modern diagnostic
#  result is a data product: it is generated by a bioinformatic pipeline,
#  interpreted against a curated database, and stored as health data subject to
#  its own legal regime.
# -----------------------------------------------------------------------------
DOMAINS: Tuple[Domain, ...] = (Domain.HEALTH, Domain.INFORMATION)

REGULATORY_STATUS = RegulatoryStatus.AUTHORISED


# =============================================================================
#  REGULATIONS
#  Grouped by which gate they control: the device, the laboratory, or the data.
# =============================================================================
REGULATIONS: Tuple[str, ...] = (
    # ---- the device ----------------------------------------------------------
    "EU Regulation (EU) 2017/746 on in vitro diagnostic medical devices, which "
    "replaced a self-certification regime with risk-classified conformity "
    "assessment and brought most laboratory-developed tests into scope",
    "US FDA 510(k) clearance and De Novo classification pathways",
    "US FDA Emergency Use Authorization, the mechanism by which outbreak "
    "assays reach clinics before full clearance",
    # ---- the laboratory --------------------------------------------------------
    "US Clinical Laboratory Improvement Amendments certification",
    "National medical laboratory licensing regimes, which vary widely",
    # ---- the data ---------------------------------------------------------------
    "GDPR Article 9, which treats health and genetic data as a special "
    "category requiring an explicit legal basis",
    "GDPR Article 22 on decisions based solely on automated processing, which "
    "reaches algorithmic interpretation of a sequencing result",
    "EU Regulation (EU) 2024/1689 on artificial intelligence, where a "
    "diagnostic interpretation model is a high-risk system",
    # ---- the patient -------------------------------------------------------------
    "Council of Europe Convention on Human Rights and Biomedicine, Article 12, "
    "restricting predictive genetic testing to health purposes",
)


# =============================================================================
#  STANDARDS
#  ISO 15189 accredits the laboratory; ISO 13485 governs the manufacturer;
#  MIQE governs whether a published result can be believed.
# =============================================================================
STANDARDS: Tuple[str, ...] = (
    # ---- the laboratory ------------------------------------------------------
    "ISO 15189 medical laboratories, requirements for quality and competence",
    "ISO 15190 medical laboratories, requirements for safety",
    "External quality assessment and proficiency testing schemes, which are the "
    "only routine check that a laboratory's answers are actually right",
    # ---- the manufacturer ------------------------------------------------------
    "ISO 13485 medical devices, quality management systems",
    "ISO 14971 application of risk management to medical devices",
    # ---- the assay ---------------------------------------------------------------
    "MIQE guidelines, minimum information for publication of quantitative "
    "real-time PCR experiments",
    "dMIQE guidelines for digital PCR",
    "CLSI EP17 evaluation of detection capability",
    "CLSI EP12 user protocol for evaluation of qualitative test performance",
    # ---- the interpretation --------------------------------------------------------
    "ACMG and AMP standards for the interpretation of sequence variants",
    "Human Genome Variation Society sequence variant nomenclature",
    "ISO 20387 biobanking, for the reference materials everything is calibrated "
    "against",
)
